problems

In [2]:
# say hello
print('hello',input())

In [ ]:
# basic datatype
print(*input().split(),sep='\n')
# print(input().replace(" ","\n"))


In [ ]:
numbers = [1, 2, 3, 4, 5]
print(*numbers)

# x = "Hello world this is a test"
# input().split() splits this into the list: ["Hello", "world", "this", "is", "a", "test"].
# * unpacks this list into individual arguments: print("Hello", "world", "this", "is", "a", "test", sep='\n').

In [ ]:
# simple calculator
x,y=map(int,input().split())  # This applies the int function to each element in the list returned by input().split()

# x= input()   # wrong
# y=input()
# x,y = input().split()   # wrong
# x,y=int(input().split())  wrong

print(x,y)
print(x,"+",y,"=",x+y)
print(x,"*",y,"=",x*y)
print(x,"-",y,"=",x-y)

In [ ]:
# difference
a,b,c,d=map(int,input().split())
print("Difference =",a*b-c*d)

In [ ]:
# area of the circle
print(3.141592653*float(input())**2)

In [ ]:
# Digits Summation
x,y=map(int,input().split())
print(x%10+y%10)

In [ ]:
# welcome to conditions
a,b=map(int,input().split())
print("Yes" if a>=b) # else "No")  #  if you don't write else it will not work

# if a>=b:
#   print("yes")

In [ ]:
# multilplies
a,b=map(int,input().split())
print('Multiples' if a%b==0 or b%a==0 else 'No Multiples')

In [ ]:
# max and min
l=*map(int,input().split()),
print(min(l),max(l))
x=l[0]
y = l[1]
z = l[2]

# if(x > y and x > z):
#   print(x)
#   if(y>z): print(y,' ',z)
#   else: print(z,' ',y)
# elif (y > x and y > z):
#   print(y)
#   if(x>z): print(x,' ',z)
#   else: print(z,' ',y)

In [ ]:
# are brothers
x= input().split();y=input().split()
print("ARE Brothers" if x[1]==y[1] else "NOT")

In [ ]:
#  Capital or Small or Digit,
x=input()
print("IS DIGIT" if x.isdigit() else "ALPHA" )
if x.isalpha(): print("IS CAPITAL" if x.isupper() else  "IS SMALL")

# ch = str(input())
# if ch.isupper():
#  print("ALPHA\nIS CAPITAL")
# elif ch.islower():
#  print("ALPHA\nIS SMALL")
# else:
#  print("IS DIGIT")

In [ ]:
# N char
print(input().swapcase())

In [ ]:
# calculator
# eval(): This function parses the input string as a Python expression and evaluates it.
print(int(eval(input())))    

h=input()   # 70000000000000000+4
symbol="+-/*"

for i in h:
    if i in symbol:
        S=i
        L=h.split(i)
 
A=int(L[0])
B=int(L[1])
 
if S=="+":
    print(A+B)
elif S=="-":
    print(A-B)
elif S=="*":
    print(A*B)
else:
    print(A//B)

LOOPS

In [1]:
i = 1;  j = 1
while i < 5 # and j < 5:      # () are optional
  print(i)
  j += 1
  # i += 1

1
1
1
1


In [3]:
for i in range(1, 5, 3):
  print(i)

1
4


In [ ]:
names = ['ali', 'ahmed', 'mohamed']
for name in names:
  print(name)

In [ ]:
animals = ['cat', 'dog', 'monkey']
print(animals)
for animal in animals:
  print(animal)

['cat', 'dog', 'monkey']
cat
dog
monkey


In [60]:
for i in range(len(animals)):
  print(animals[i])

cat
dog
monkey


In [61]:
nums = [0, 1, 2, 3, 4]
# squares = []
# for x in nums:
#   squares.append(x ** 2)
squares = [i**2 for i in nums]
print(squares)

[0, 1, 4, 9, 16]


In [ ]:
N = 5
arr = [0 for i in range(N)]
print(arr)

In [4]:
N = 5
ar = [0]*N
print(ar)

[0, 0, 0, 0, 0]


In [ ]:
rows, cols = (5, 5)
arr = [[[0]*cols]*rows * 2] * 1 * 3
for row in arr:
  print(row)

In [62]:
dim1, dim2, dim3, dim4, dim5 = 3, 3, 3, 3, 3  # Example dimensions, you can change them

array_5d = [[[[[0 for _ in range(dim5)] for _ in range(dim4)] for _ in range(dim3)] for _ in range(dim2)] for _ in range(dim1)]
print(array_5d)

[[[[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]], [[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]], [[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]]], [[[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]], [[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]], [[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]]], [[[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]], [[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]], [[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]]]]


In [7]:
rows, cols = (5, 5)
arr = [[0]*cols]*rows        # you are creating multiple references to the same inner list.
print(arr, "before")

arr[0][0] = 1 # update only one element
print(arr, "after")

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]] before
[[1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0]] after


In [8]:
rows, cols = (5, 5)
arr = [[0]*cols for _ in range(rows)]
print(arr, "before")

arr[0][0] = 1  # update only one element
print(arr, "after")


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]] before
[[1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]] after


In [ ]:
rows, cols = (5, 5)
arr = [[0 for i in range(cols)] for j in range(rows)]
print(arr)

In [ ]:
rows, cols = (5, 5)
for i in range(cols):
  for j in range(rows):
    arr[i][j] = 0
    # arr[i].append(5)
print(arr)

In [ ]:
arr=[]
rows, cols=5,5
for i in range(rows):
    col = []
    for j in range(cols):
        col.append(0)
    arr.append(col)
print(arr)

In [ ]:
for row in arr:
    print(row)

tuple

In [6]:
my_tuple = (1, 2, 3, 4, 'end')
print("Tuple:", my_tuple)

# Attempting to modify the tuple will raise an error
# my_tuple[0] = 10  # This will raise a TypeError

# Accessing elements in a tuple
print("First element of the tuple:", my_tuple[0])

# Tuples can be concatenated to create a new tuple
new_tuple = my_tuple + (6,)
print("Concatenated Tuple:", new_tuple)

# Tuples can be used as keys in a dictionary because they are immutable
my_dict = {my_tuple: "A collection of numbers"}
print("Dictionary with a tuple key:", my_dict)

Tuple: (1, 2, 3, 4, 5)
First element of the tuple: 1
Concatenated Tuple: (1, 2, 3, 4, 5, 6)
Dictionary with a tuple key: {(1, 2, 3, 4, 5): 'A collection of numbers'}


In [ ]:
# You cannot remove items in a tuple.
thistuple = ("apple", "banana", "cherry")
del thistuple
print(thistuple) #this will raise an error because the tuple no longer exists

enumerate

In [5]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
  # print('#%d: %s' % (idx + 1, animal))
  print('#',idx,animals[idx])

# 0 cat
# 1 dog
# 2 monkey


In [8]:
l1 = ["eat", "sleep", "repeat"]
s1 = "geek"

# creating enumerate objects
obj1 = enumerate(l1)
obj2 = enumerate(s1)

print(obj1)
print ("Return type:", type(obj1))

print (list(obj1))  # only be iterated over once if i run again will return null
print (list(obj2))

# changing start index to 2 from 0

print(list(enumerate(s1, 2)))

Return type: <class 'enumerate'>
[(0, 'eat'), (1, 'sleep'), (2, 'repeat')]
[(0, 'g'), (1, 'e'), (2, 'e'), (3, 'k')]
[(2, 'g'), (3, 'e'), (4, 'e'), (5, 'k')]


In [ ]:
my_list = []
help(my_list.append)

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

In [ ]:
def print(x):
  print('hello,',x)

In [ ]:
print('ali')

In [ ]:
def sign(x):
  if x > 0:
    return 'positive'
  elif x < 0:
    return 'negative'
  else:
    return 'zero'
for x in [-1, 0, 1]:
  print(sign(x))

In [ ]:
def square(number):
  return number * number
result = square(2)
print(result)

In [1]:
d = {'cat': 'cute', 'dog': 'furry'} # Create a new dictionary with some data
print(d['cat']) # Get an entry from a dictionary; prints "cute"

print('cat' in d) # Check if a dictionary has a given key; prints "True"

print(d['fish']) # error not found

d['fish'] = 'wet' # Set an entry in a dictionary

print(d['fish']) # Prints "wet"

# print(d['monkey']) # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A')) # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A')) # Get an element with a default; prints "wet"
del d['fish'] # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

cute
True


KeyError: 'fish'

numpy

In [18]:
import numpy as np

# Creating array object
# arr = np.array( [[ 1, 2, 3],
#                  [ 4, 2, 5]] )
arr = np.array([1,2,3])
# arr = np.array( [
#     [[[1],[2],[3]], [[2],[3],[4]], [[3],[4],[5]]],
#     [[[4],[5],[6]], [[2],[7],[8]], [[5],[9],[2]]]
#     ])

arr[0] = 5

print(arr)

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)        # numpy choose the datatype

[5 2 3]
Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  1
Shape of array:  (3,)
Size of array:  3
Array stores elements of type:  int64


In [34]:
import numpy as np

# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a.shape)


# Creating array from tuple
tuple = (1 , 3, 2)
b = np.array(tuple)
print ("\nArray created using passed tuple:\n", b)

b[0] = 5
print(b)

Array created using passed list:
 (2, 3)

Array created using passed tuple:
 [1 3 2]
[5 3 2]


In [42]:
import numpy as np
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))

print(np.sqrt(x))


print('\n')
print('x',x)
print('y',y)


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


x [[1. 2.]
 [3. 4.]]
y [[5. 6.]
 [7. 8.]]


In [52]:
list = [1,2,3,4]
a = np.array([list])
print(a.shape)    #a.shape()  wrong
print(a.ndim)   # represents the number of dimensions (axes) of the ndarray
# a.flatten()
# a.ravel()
print(a.shape)

(1, 4)
2
(1, 4)


In [45]:
condition = [True, False, True, False]  # This condition array is the same length as the last dimension of 'a'
compressed_array = a.compress(condition, axis=1)
print("Compressed array:", compressed_array)


Compressed array: [[1 3]]


In [49]:
reshaped_array = a.reshape(2, 2)
print("Reshaped array shape:", reshaped_array.shape)  # Output: (2, 2)
print("Reshaped array:\n", reshaped_array)


Reshaped array shape: (2, 2)
Reshaped array:
 [[1 2]
 [3 4]]


In [48]:
flattened_array = a.flatten()
print("Flattened array shape:", flattened_array.shape)  # Output: (4,)
print("Flattened array:", flattened_array)


Flattened array shape: (4,)
Flattened array: [1 2 3 4]


In [51]:
# raveled_array = a.ravel()
# print("Raveled array shape:", raveled_array.shape)  # Output: (4,)
# print("Raveled array:", raveled_array)


In [54]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
# Inner product of vectors;
# print(v.dot(w))
# print(np.dot(v, w))
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
# [43 50]]
# print(x.dot(y))
# print(np.dot(x, y))

[29 67]
[29 67]


In [57]:
print(x.T)

[[1 3]
 [2 4]]


In [56]:
print(np.sum(x)) # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0)) # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [58]:
print(x+v)
print(x+y)

[[10 12]
 [12 14]]
[[ 6  8]
 [10 12]]


In [59]:
print(v+x)       # is the same x + v

[[10 12]
 [12 14]]
